### ISSUE TITLE
`docker-compose build` likely permission issue

### ISSUE THREAD

**Issue by cannadayr** [gordonguthrie/rappel#1]
I am getting the following error when running `docker-compose build` (leaving out successful steps):
```
Step 19/24 : RUN export uid=501 gid=20 &&     mkdir -p /home/developer &&     echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd &&     echo "developer:x:${uid}:" >> /etc/group &&     echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer &&     chmod 0440 /etc/sudoers.d/developer &&     chown ${uid}:${gid} -R /home/developer &&     mkdir /home/developer/.mix &&     chown ${uid}:${gid} -R /home/developer/.mix &&      mix local.hex --force &&        mix archive.install hex phx_new 1.4.12 --force
 ---> Running in 8f12883d0232
* creating root/.mix/archives/hex-0.20.5
Failed to fetch record for 'hexpm/phx_new' from registry (using cache instead)
Failed to check for new Hex version
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], :nxdomain}]}
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], :nxdomain}]}
** (Mix) No package with name phx_new (from: mix.exs) in registry
ERROR: Service 'rappel' failed to build: The command '/bin/sh -c export uid=501 gid=20 &&     mkdir -p /home/developer &&     echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd &&     echo "developer:x:${uid}:" >> /etc/group &&     echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer &&     chmod 0440 /etc/sudoers.d/developer &&     chown ${uid}:${gid} -R /home/developer &&     mkdir /home/developer/.mix &&     chown ${uid}:${gid} -R /home/developer/.mix &&      mix local.hex --force &&         mix archive.install hex phx_new 1.4.12 --force' returned a non-zero code: 1
```

If I rerun `docker-compose build`, I get the following error:
```
Step 19/24 : RUN export uid=501 gid=20 &&     mkdir -p /home/developer &&     echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd &&     echo "developer:x:${uid}:" >> /etc/group &&     echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer &&     chmod 0440 /etc/sudoers.d/developer &&     chown ${uid}:${gid} -R /home/developer &&     mkdir /home/developer/.mix &&     chown ${uid}:${gid} -R /home/developer/.mix &&      mix local.hex --force &&        mix archive.install hex phx_new 1.4.12 --force
 ---> Running in 70342c4aca8b
** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], :nxdomain}]}

Could not run archive.install for:

    https://repo.hex.pm/installs/1.9.0/hex-0.20.5.ez

Please download the contents above manually to your current directory and run:

    mix archive.install ./hex-0.20.5.ez

ERROR: Service 'rappel' failed to build: The command '/bin/sh -c export uid=501 gid=20 &&     mkdir -p /home/developer &&     echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd &&     echo "developer:x:${uid}:" >> /etc/group &&     echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer &&     chmod 0440 /etc/sudoers.d/developer &&     chown ${uid}:${gid} -R /home/developer &&     mkdir /home/developer/.mix &&     chown ${uid}:${gid} -R /home/developer/.mix &&      mix local.hex --force &&         mix archive.install hex phx_new 1.4.12 --force' returned a non-zero code: 1
```

If I attempt to start the container anyways with `docker-compose up`, I get the following:
```
docker-compose up
Building rappel
Step 1/24 : FROM elixir:1.9.4
 ---> d22a04d088ca
Step 2/24 : USER root
 ---> Using cache
 ---> 10e1779f5885
Step 3/24 : RUN apt-get update
 ---> Using cache
 ---> 010c2a0825ca
Step 4/24 : RUN apt-get install -y git
 ---> Using cache
 ---> 9919182e920b
Step 5/24 : RUN apt-get install -y make
 ---> Using cache
 ---> af59844da390
Step 6/24 : RUN apt-get install -y unzip
 ---> Using cache
 ---> b2d0ae947271
Step 7/24 : RUN apt-get install -y lynx
 ---> Using cache
 ---> fc2ca66f7139
Step 8/24 : RUN apt-get install -y emacs
 ---> Using cache
 ---> ee8eaa38f4d2
Step 9/24 : RUN apt-get install -y wget
 ---> Using cache
 ---> 48569a17246b
Step 10/24 : RUN apt-get install -y nodejs
 ---> Using cache
 ---> 9dd074765b3e
Step 11/24 : RUN apt-get install -y npm
 ---> Using cache
 ---> d89e25565a42
Step 12/24 : RUN apt-get install -y postgresql postgresql-contrib
 ---> Using cache
 ---> 46e4d7ff112d
Step 13/24 : RUN apt-get install -y sudo
 ---> Using cache
 ---> 42214d7ec425
Step 14/24 : RUN apt-get install -y lsof
 ---> Using cache
 ---> ae71306d7780
Step 15/24 : RUN apt-get install -y net-tools
 ---> Using cache
 ---> e6a5e11ca25a
Step 16/24 : RUN apt-get install -y x11-apps
 ---> Using cache
 ---> 952e85554f86
Step 17/24 : RUN apt-get install -y pgadmin3
 ---> Using cache
 ---> 5a9ed73dce75
Step 18/24 : RUN apt-get install -y tree
 ---> Using cache
 ---> 25d39d9d6720
Step 19/24 : RUN export uid=501 gid=20 &&     mkdir -p /home/developer &&     echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd &&     echo "developer:x:${uid}:" >> /etc/group &&     echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer &&     chmod 0440 /etc/sudoers.d/developer &&     chown ${uid}:${gid} -R /home/developer &&     mkdir /home/developer/.mix &&     chown ${uid}:${gid} -R /home/developer/.mix &&      mix local.hex --force &&        mix archive.install hex phx_new 1.4.12 --force
 ---> Running in 46ec4653d039
* creating root/.mix/archives/hex-0.20.5
Resolving Hex dependencies...
Dependency resolution completed:
New:
  phx_new 1.4.12
* Getting phx_new (Hex package)
All dependencies are up to date
Compiling 10 files (.ex)
Generated phx_new app
Generated archive "phx_new-1.4.12.ez" with MIX_ENV=prod
* creating /root/.mix/archives/phx_new-1.4.12
Removing intermediate container 46ec4653d039
 ---> b2e34816738a
Step 20/24 : RUN usermod -aG sudo developer
 ---> Running in dde467c703a3
Removing intermediate container dde467c703a3
 ---> a5022a71caf6
Step 21/24 : USER developer
 ---> Running in 2bd202b660e2
Removing intermediate container 2bd202b660e2
 ---> bc87ea3e3c60
Step 22/24 : RUN mix local.hex --force
 ---> Running in b94f797a4938
* creating home/developer/.mix/archives/hex-0.20.5
Removing intermediate container b94f797a4938
 ---> 4a4edcf5d45f
Step 23/24 : RUN mix local.rebar rebar3 /usr/local/bin/rebar3 --force
 ---> Running in 5c88ebf882f5
* creating home/developer/.mix/rebar3
Removing intermediate container 5c88ebf882f5
 ---> 8fb5cbdbaaba
Step 24/24 : CMD tail -f /dev/null
 ---> Running in 7fe95b8c2818
Removing intermediate container 7fe95b8c2818
 ---> b1205f8b3e20

Successfully built b1205f8b3e20
Successfully tagged rappel_rappel:latest
WARNING: Image for service rappel was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating rappel_rappel_1 ... done
Attaching to rappel_rappel_1
```

I am then able to connect to the container using `start_rappel.sh`, however I get the following from inside the container:
```
$ iex -S mix phx.server
Erlang/OTP 22 [erts-10.7.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

** (File.Error) could not make directory (with -p) "/rappel/_build/dev/lib/lfe": no such file or directory
    (elixir) lib/file.ex:314: File.mkdir_p!/1
    (mix) lib/mix/tasks/deps.compile.ex:188: Mix.Tasks.Deps.Compile.do_rebar3/2
    (mix) lib/mix/tasks/deps.compile.ex:84: anonymous fn/4 in Mix.Tasks.Deps.Compile.compile/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/deps.compile.ex:65: Mix.Tasks.Deps.Compile.compile/2
    (mix) lib/mix/tasks/deps.loadpaths.ex:89: Mix.Tasks.Deps.Loadpaths.deps_check/2
    (mix) lib/mix/tasks/deps.loadpaths.ex:28: Mix.Tasks.Deps.Loadpaths.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
```

More succinctly, it seems to be a permission issue:
```
developer@3c661ebf6a38:/rappel$ mkdir _build
mkdir: cannot create directory ‘_build’: Permission denied`
```

Here are the environment variables inside docker:
```
developer@3c661ebf6a38:/rappel$ env
HOSTNAME=3c661ebf6a38
PWD=/rappel
REBAR_VERSION=2.6.4
HOME=/home/developer
LANG=C.UTF-8
TERM=xterm
OTP_VERSION=22.3.4
REBAR3_VERSION=3.13.2
DISPLAY=host.docker.internal:0
SHLVL=1
ELIXIR_VERSION=v1.9.4
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
OLDPWD=/tmp
_=/usr/bin/env
```

Steps I have taken:
1. cloned lfe to a sibling directory
2. Followed post-installation steps as documented here: https://docs.docker.com/engine/install/linux-postinstall/ . Confirmed that I can run docker cmds as a non-root user including `hello-world` test.
3. Confirmed that I have network connection inside the container. `ping`, `wget`, and `lynx` all appear to be working.

I am not a frequent docker user, so its likely I have not set up permissions correctly. Let me know if you need anything else or if I should direct question elsewhere!

**Comment by cannadayr** [comment]
Figured out the underlying issue. Just had to take a closer look at the Dockerfile.

Needs the local users uid/gid.

I am still getting some commands failing the first 2 times I run `docker-compose build`, so I will break out the commands into individual steps to determine whats happening.

I will also look into ways of letting the user set the appropriate UID/GID on build and include that in the documentation.
