### ISSUE TITLE
protocol Enumerable not implemented for...

### ISSUE THREAD

**Issue by cannadayr** [gordonguthrie/rappel#3]
Getting this error when entering commands into web interface. Attempted with both `master` and `development` branches of pometo.

Ran from docker container, see output below:

```
got an enter: "1.1 + 2.2"
lexed: [
  {:float, 1, 1, '1.1', 1.1},
  {:scalar_fn, 1, 5, '+', '+'},
  {:float, 1, 7, '2.2', 2.2}
]
parsed: {:expr, :scalar, :dyadic, '+',
 [
   {:"__⍴__", :eager, false, :float, [1], [1.1]},
   {:"__⍴__", :eager, false, :float, [1], [2.2]}
 ]}
results: {:"__⍴__", :eager, false, :undefined, [1], [3.3000000000000003]}
[error] GenServer #PID<0.2149.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:"__⍴__", :eager, false, :undefined, [1], [3.3000000000000003]} of type Tuple. This protocol is implemented for the following type(s): File.Stream, MapSet, Function, HashDict, Range, Date.Range, Map, List, Stream, IO.Stream, GenEvent.Stream, HashSet
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:3023: Enum.reduce/3
    (rappel_web) lib/rappel_web/live/page_live.html.leex:4: anonymous fn/2 in RappelWeb.PageLive.render/1
    (phoenix_live_view) lib/phoenix_live_view/diff.ex:208: Phoenix.LiveView.Diff.traverse/5
    (phoenix_live_view) lib/phoenix_live_view/diff.ex:288: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_dynamic/5
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view) lib/phoenix_live_view/diff.ex:208: Phoenix.LiveView.Diff.traverse/5
    (phoenix_live_view) lib/phoenix_live_view/diff.ex:92: Phoenix.LiveView.Diff.render/3
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:504: Phoenix.LiveView.Channel.render_diff/2
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:361: Phoenix.LiveView.Channel.handle_changed/4
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "11", payload: %{"event" => "on_enter", "type" => "form", "value" => "q=1.1+%2B+2.2"}, ref: "23", topic: "lv:phx-HHHHHHHHH"}
State: %{components: {%{}, %{}, 0}, join_ref: "11", serializer: Phoenix.Socket.V2.JSONSerializer, socket: #Phoenix.LiveView.Socket<assigns: %{flash: %{}, lexer: %{}, live_action: :index, live_module: RappelWeb.PageLive, main: %{}, parser: %{}, query: "1.1 + 2.2"}, changed: %{}, endpoint: RappelWeb.Endpoint, id: "phx-HHHHHHHHH", parent_pid: nil, root_pid: #PID<0.2149.0>, router: RappelWeb.Router, view: RappelWeb.PageLive, ...>, topic: "lv:phx-HHHHHHHHH", transport_pid: #PID<0.2138.0>, uri: %URI{authority: nil, fragment: nil, host: "localhost", path: nil, port: 4000, query: nil, scheme: "http", userinfo: nil}}
```

**Comment by cannadayr** [comment]
This has been fixed by recent changes. Closing.
